x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false
  images:
    '':
      properties:
        image.repository:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG
    kube-rbac-proxy:
      properties:
        kubeRbacProxy.image:
          type: FULL
  clusterConstraints:
    k8sVersion: ">=1.18.1"
    resources:
    - replicas: 1
      requests:
        cpu: 100m
        memory: 300Mi
      affinity:
        simple NodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
          minimumNodeCount: 1
    istio:
      type: UNSUPPORTED
  deployerServiceAccount:
    description: Creates app resources, including Webhooks and ClusterRoleBindings.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
            - 'rbac.authorization.k8s.io'
            resources:
            - 'clusterroles'
            - 'clusterrolebindings'
            verbs:
            - '*'
          - apiGroups: 
            - 'apiextensions.k8s.io'
            resources: 
            - 'customresourcedefinitions'
            verbs: 
            - '*'
          - apiGroups:
            - ''
            resources:
            - 'namespaces'
            verbs:
            - 'create'
            - 'list'
            - 'update'
            - 'patch'
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
- name
- namespace
